### ISSUE TITLE
Can't get it working...

### ISSUE THREAD

**Issue by svdoever** [sindresorhus/yo-app#1]
Tried to get the code base working, but I don't get the output in the Node-Webkit window.

Actually I try to get a UI working in the github Electron shell. I would like to have an Adapter for Yeoman to ask the prompt questions in a browser window. Tried oart of your code, but could not get that working either. Anyother  examples on how to integrate Yeoman in a web UI?

**Comment by arthurvr** [comment]
Check the readme. This app is deprecated so I'm going to close the issue.

**Comment by svdoever** [comment]
Ok, any pointers to examples that have a web ui on top of Yeoman generators?

**Comment by sindresorhus** [comment]
// @stefanbuck @ruyadorno

**Comment by stefanbuck** [comment]
Hi @svdoever, 
we're working on a replacement to fill the gap. A first developer version will be available soon. Stay tuned!

**Comment by svdoever** [comment]
Hi @stefanbuck, looking forward to it. Want to integrate Yeoman with GitHub Electron.

**Comment by stefanbuck** [comment]
... you will be surprised :gift:

**Comment by svdoever** [comment]
Any timeframe? Now trying to get your code on yoapp working... :-)

**Comment by ruyadorno** [comment]
@svdoever we set the upcoming **27 june** as the "make the repo public" date.

Be aware that we are working towards the same goal within the Yeoman org (to create an ui working on top of electron shell) also, we would be very happy to have developers like you jumping in and helping us with the effort to finish it :smile:

Now, to help you with your original question, this: http://yeoman.io/authoring/integrating-yeoman.html is one of the references we used to implement the adapter within our app.

**Comment by volkrass** [comment]
@ruyadorno can't find the yoapp public repo. Is it there?

**Comment by svdoever** [comment]
Hi @ruyadorno , any news on the ui on top of Electron Shell? I have version working, but am very interested to see your solution!

**Comment by arthurvr** [comment]
@volkrass @svdoever We're planning to make it public really soon. Just give it another few days.

**Comment by ruyadorno** [comment]
thanks @arthurvr :+1:

**Comment by ruyadorno** [comment]
@svdoever we just made the repo public :smile: 

https://github.com/yeoman/yeoman-app

Please join us and help making it to the **v1.0.0-beta1** release!
